message:
  not-player: "§cOnly players can run this command!"
  unknown-command: "§cUnknown command!"
  missing-arg: "§cMissing arguments!"
  missing-perm: "§cYou dont have permission to run this command!"
  config-reload: "§aConfiguration has now been reloaded!"
  many-arg: "§cToo many arguments!"
  few-arg: "§cMissing arguments!"
  unknown-cmd-arg: "§cUnknown command arguments!"
  mat-not-found: "§cItem not found!"

  waystone-created: "§aWaystone created!"
  waystone-name-conflict: "§cA waystone already exist!"
  waystone-deleted: "§aWaystone deleted!"
  waystone-not-found: "§cCould not find a waystone with that name!"
  waystone_banned: "§cYou're banned from using this waystone!"

  waystone_teleported: "§aYou teleported to %waystone_name%!"

  saving-error: "§cCould not save waystone file!"
  delete-error: "§cCould not delete waystone from file!"
  load-error: "§cCould not load waystones from file!"
  world-load-error: "§cCould not load waystones from file because %world% dont exist!"

  teleport_start: "§eTeleport will start, please §6stand still§e!"
  teleport_countdown: "§eTeleporting in §6%countdown_left% §e… §7(Don't move)"
  teleport_cancelled: "§cTeleport cancelled because you moved. §7You need to stand still!"
  teleport_success: "§aTeleported!"

inventory:
  title: "Where would you like to travel?"
  click-sound: ""
  size: 54

sound:
  teleport_start: "minecraft:ui.button.click"
  teleport_tick: "minecraft:block.note_block.hat"
  teleport_cancelled: "minecraft:block.anvil.land"
  teleport_success: "minecraft:entity.enderman.teleport"
  inventory_click: "minecraft:ui.button.click"
options:
  hitbox:
    offset:
      - 0
      - 0
      - 0
    size:
      - 2
      - 4
  statue:
    offset:
      - 0
      - 3.1
      - 0
    size:
      - 2
      - 2
      - 2
  pedestal:
    offset:
      - 0
      - 1
      - 0
    size:
      - 2
      - 2
      - 2
  teleport:
    offset:
      - 3 # Forward/Backwards
      - 0 # Up/Down
      - 0 # Left/Right
    delay: 3
    countdown: true